routes/web.php
<?php

use Illuminate\Support\Facades\Route;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('welcome');

Auth::routes(['verify' => true]);

// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('/email/verify', function () {
    return view('auth.verify');
})->middleware('auth')->name('verification.notice');

Route::get('/forgot-password', function () {
    return view('auth.passwords.email');
})->middleware('guest')->name('password.request');









// superadmin
Route::group([
	'middleware' => ['role:Super-Admin', 'auth', 'verified'],
	'prefix'     => 'super-admin',
], function () {
    Route::get('/', [App\Http\Controllers\Superadmin\DashboardController::class, 'index'])->name('super-admin.page');
    Route::resource('role', App\Http\Controllers\Superadmin\RoleController::class);
    Route::resource('user', App\Http\Controllers\Superadmin\UserController::class, [
    	'except' => [
    		'destroy',
    		'show',
    	],
    ]);
    Route::resource('size', App\Http\Controllers\Superadmin\SizeController::class);
    Route::resource('category', App\Http\Controllers\Superadmin\CategoryController::class);
    Route::resource('ingredient', App\Http\Controllers\Superadmin\IngredientController::class);
    Route::resource('product', App\Http\Controllers\Superadmin\ProductController::class, [
		'except' => [
			'edit',
			'update',
		],
		'names'  => [
			'index'   => 'superadmin-product.index',
			'create'  => 'superadmin-product.create',
			'store'   => 'superadmin-product.store',
			'show'    => 'superadmin-product.show',
			'destroy' => 'superadmin-product.destroy',
    	],
    ]);
    Route::get('laporan', [App\Http\Controllers\Superadmin\LaporanController::class, 'index'])->name('superadmin.laporan');
    Route::get('laporan/generate-ingredient-terpakai', [App\Http\Controllers\Superadmin\LaporanController::class, 'generateIngredientTerpakai'])->name('superadmin.laporan-ingredient-terpakai');

	Route::get('ingredient-image/{ingredientId}', [App\Http\Controllers\Superadmin\IngredientImageController::class, 'getImageItemsByItem'])->name('ingredient-image');
	Route::post('ingredient-image/{ingredientId}', [App\Http\Controllers\Superadmin\IngredientImageController::class, 'storeImageItemsByItem'])->name('ingredient-image.store');
	Route::delete('ingredient-image/{ingredientId}', [App\Http\Controllers\Superadmin\IngredientImageController::class, 'deleteImageItemsById'])->name('ingredient-image.destroy');

	Route::get('update-from-email/{productId}', [App\Http\Controllers\Superadmin\ProductController::class, 'updateFromEmail'])->name('superadmin.update-from-email');
	Route::get('restock', [App\Http\Controllers\Superadmin\RestockController::class, 'index'])->name('superadmin-restock.index');
	Route::get('accept-restock/{id}', [App\Http\Controllers\Superadmin\RestockController::class, 'acceptRestock'])->name('accept-restock');
});









// produksi
Route::group([
	'middleware' => ['role:Produksi', 'auth', 'verified'],
	'prefix'     => 'produksi',
], function () {
    Route::get('/', [App\Http\Controllers\Produksi\DashboardController::class, 'index'])->name('produksi.page');
    Route::get('ingredient', [App\Http\Controllers\Produksi\IngredientController::class, 'index'])->name('produksi-ingredient.index');
    Route::get('ingredient-image/{id}', [App\Http\Controllers\Produksi\IngredientController::class, 'image'])->name('produksi-ingredient-image');
    Route::resource('product', App\Http\Controllers\Produksi\ProductController::class, [
		'except' => [
			'edit',
			'update',
		],
		'names'  => [
			'index'   => 'produksi-product.index',
			'create'  => 'produksi-product.create',
			'store'   => 'produksi-product.store',
			'show'    => 'produksi-product.show',
			'destroy' => 'produksi-product.destroy',
    	]
    ]);
});









// pegawai
Route::group([
	'middleware' => ['role:Pegawai', 'auth', 'verified'],
	'prefix'     => 'pegawai',
], function () {
    Route::get('/', [App\Http\Controllers\Pegawai\DashboardController::class, 'index'])->name('pegawai.page');
    Route::resource('suplier', App\Http\Controllers\Pegawai\SuplierController::class, [
    	'except' => [
    		'destroy',
    		'show',
    	],
    ]);
    Route::resource('ingredient', App\Http\Controllers\Pegawai\IngredientController::class, [
		'except' => [
			'show',
		],
		'names'  => [
			'index'   => 'pegawai-ingredient.index',
			'create'  => 'pegawai-ingredient.create',
			'store'   => 'pegawai-ingredient.store',
			'edit'    => 'pegawai-ingredient.edit',
			'update'  => 'pegawai-ingredient.update',
			'destroy' => 'pegawai-ingredient.destroy',
    	]
    ]);

	Route::get('ingredient-image/{id}', [App\Http\Controllers\Pegawai\IngredientController::class, 'getImageItemsByItem'])->name('pegawai-ingredient-image');
	Route::post('ingredient-image/{id}', [App\Http\Controllers\Pegawai\IngredientController::class, 'storeImageItemsByItem'])->name('pegawai-ingredient-image.store');
	Route::delete('ingredient-image/{id}', [App\Http\Controllers\Pegawai\IngredientController::class, 'deleteImageItemsById'])->name('pegawai-ingredient-image.destroy');
});









// suplier
Route::group([
	'middleware' => ['role:Suplier', 'auth', 'verified'],
	'prefix'     => 'suplier',
], function () {
    Route::get('/', [App\Http\Controllers\Suplier\DashboardController::class, 'index'])->name('suplier.page');
    Route::get('ingredient', [App\Http\Controllers\Suplier\IngredientController::class, 'index'])->name('suplier-ingredient.index');
    Route::get('ingredient-image/{id}', [App\Http\Controllers\Suplier\IngredientController::class, 'image'])->name('suplier-ingredient-image');
    Route::resource('/restock', App\Http\Controllers\Suplier\RestockController::class, [
		'except' => [
			'edit',
			'update',
		],
		'names'  => [
			'index'   => 'suplier-restock.index',
			'create'  => 'suplier-restock.create',
			'store'   => 'suplier-restock.store',
			'destroy' => 'suplier-restock.destroy',
    	]
    ]);
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable implements MustVerifyEmail
{
    use HasFactory, Notifiable, HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    // ingretdients relation
    public function ingredients()
    {
        return $this->hasMany(Ingredient::class, 'suplier_id');
    }

    // productss relation
    public function products()
    {
        return $this->hasMany(Product::class, 'produksi_id');
    }
}

app/Http/Controllers/Superadmin/CategoryController.php
<?php

namespace App\Http\Controllers\Superadmin;

use App\Http\Controllers\Controller;
use App\Models\Category;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::all();

        return view('superadmin.category.index', ['categories' => $categories]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('superadmin.category.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'category' => 'required',
        ]);

        Category::create([
            'category' => $request->category,
        ]);

        return redirect()->back()->with('success', 'Category created!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        return view('superadmin.category.edit', ['category' => $category]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Category $category)
    {
        $category->update($request->all());

        return redirect()->back()->with('success', 'Category updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        if (count($category->items) > 0) {
            return redirect()->back()->with('error', "Can't remove this category. This category has items!");
        }

        $category->delete();
        return redirect()->back()->with('success', 'Category successfully removed!');
    }
}

app/Http/Controllers/Superadmin/DashboardController.php
<?php

namespace App\Http\Controllers\Superadmin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class DashboardController extends Controller
{
    // index
    public function index()
    {
    	return view('superadmin.dashboard');
    }
}

app/Http/Controllers/Superadmin/IngredientController.php
<?php

namespace App\Http\Controllers\Superadmin;

use App\Http\Controllers\Controller;
use App\Models\Ingredient;
use App\Models\Category;
use App\Models\User;
use App\Models\Size;
use Illuminate\Http\Request;
use Storage;

class IngredientController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $ingredients = Ingredient::with('suplier')
                       ->with('category')
                       ->with('size')
                       ->orderBy('suplier_id', 'desc')
                       ->get();

        return view('superadmin.ingredient.index', ['ingredients' => $ingredients]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all();
        $supliers   = User::whereHas('roles', function ($query) {
                        $query->where('roles.name', 'Suplier');
                      })->get();
        $sizes      = Size::all();

        return view('superadmin.ingredient.create', [
            'categories' => $categories,
            'supliers'   => $supliers,
            'sizes'      => $sizes,
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'category_id' => 'required',
            'suplier_id'  => 'required',
            'size_id'     => 'required',
            'name'        => 'required',
            'price'       => 'required',
            'quantity'    => 'required',
        ]);

        Ingredient::create($request->all());

        return redirect()->back()->with('success', 'Ingredient created!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Ingredient  $ingredient
     * @return \Illuminate\Http\Response
     */
    public function show(Ingredient $ingredient)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Ingredient  $ingredient
     * @return \Illuminate\Http\Response
     */
    public function edit(Ingredient $ingredient)
    {
        $categories = Category::all();
        $supliers   = User::whereHas('roles', function ($query) {
                        $query->where('roles.name', 'Suplier');
                      })->get();
        $sizes      = Size::all();

        return view('superadmin.ingredient.edit', [
            'ingredient' => $ingredient,
            'categories' => $categories,
            'supliers'   => $supliers,
            'sizes'      => $sizes,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Ingredient  $ingredient
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Ingredient $ingredient)
    {
        $request->validate([
            'category_id' => 'required',
            'suplier_id'  => 'required',
            'size_id'     => 'required',
            'name'        => 'required',
            'price'       => 'required',
            'quantity'    => 'required',
        ]);

        $ingredient->update($request->all());

        return redirect()->back()->with('success', 'Ingredient updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Ingredient  $ingredient
     * @return \Illuminate\Http\Response
     */
    public function destroy(Ingredient $ingredient)
    {
        $ingredient->ingredientImages->map(function ($image) {
            Storage::delete($image->path);
            $image->delete();
        });

        $ingredient->delete();

        return redirect()->back()->with('success', 'Ingredient successfully removed!');
    }
}

app/Http/Controllers/Superadmin/IngredientImageController.php
<?php

namespace App\Http\Controllers\Superadmin;

use App\Http\Controllers\Controller;
use App\Models\Ingredient;
use App\Models\IngredientImage;
use Illuminate\Http\Request;
use Storage;

class IngredientImageController extends Controller
{
    // get image items by ingredient
    public function getImageItemsByItem($ingredientId)
    {
        $ingredient = Ingredient::with('ingredientImages')->find($ingredientId);

        return view('superadmin.ingredient.ingredient-image', ['ingredient' => $ingredient]);
    }

    // store image items by item
    public function storeImageItemsByItem(Request $request, $ingredientId)
    {
        $request->validate([
            'image' => 'required|file|max:2000',
        ]);

        $path = Storage::putFile(
                    'public/images',
                    $request->file('image'),
                );

        IngredientImage::create([
            'ingredient_id' => $ingredientId,
            'path'          => $path,
        ]);

        return redirect()->back()->with('success', 'Image item uploaded!');
    }

    public function deleteImageItemsById($imageItem)
    {
        $file = IngredientImage::find($imageItem);

        Storage::delete($file->path);
        $file->delete();

        return redirect()->back()->with('success', 'Image item removed!');
    }
}

app/Http/Controllers/Superadmin/LaporanController.php
<?php

namespace App\Http\Controllers\Superadmin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Product;
use PDF;

class LaporanController extends Controller
{
	public function index()
	{
		return view('superadmin.laporan.index');
	}

	public function generateIngredientTerpakai(Request $request)
	{
		$part = $request->query()['part'];

		if ($part == 'all') {
			$products = Product::with('ingredients.suplier')
			->where('status', 'READY')
			->get();
		}

		$name = 'Laporan-Ingredient-Terpakai-' . date('YmdHis');

		$pdf  = PDF::loadview('superadmin.laporan.ingredient-terpakai', [
			'products' => $products,
			'name'     => $name,
		]);

    	return $pdf->download($name);

    	// return redirect()->back()->with('success', 'Laporan generated!');
	}
}

app/Http/Controllers/Superadmin/RestockController.php
<?php

namespace App\Http\Controllers\Superadmin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Restock;
use App\Mail\AcceptRestock;
use Illuminate\Support\Facades\Mail;

class RestockController extends Controller
{
	public function index()
	{
		$restocks = Restock::with('ingredient')->get();

		return view('superadmin.restock.index', [
			'restocks' => $restocks,
		]);
	}

	public function acceptRestock($id)
	{
		$restock = Restock::with('ingredient.suplier')->find($id);

		$restock->status = 'ACCEPT';
		$restock->save();

		$restock->ingredient->update([
			'quantity' => $restock->ingredient->quantity + $restock->quantity,
		]);

		Mail::to($restock->ingredient->suplier->email)->queue(new AcceptRestock($restock->ingredient->suplier->name, $restock->ingredient->name));

		return redirect()->back()->with('success', 'Restock accept!');
	}
}

resources/views/superadmin/user/create.blade.php
@extends('adminlte::page')

@section('title', 'Create User')

@section('content_header')
    <div class="row">
        <div class="col-md-6">
            <h1 class="m-0 text-dark d-inline">Create user</h1>
            <a href="{{ route('user.index') }}" class="btn btn-secondary float-right"><i class="fas fa-arrow-left"></i> Back</a>

            @if(session('success'))
                <div class="alert alert-success alert-block mt-4">
                    <button type="button" class="close" data-dismiss="alert">×</button>
                    <strong>{{ session('success') }}</strong>
                </div>
            @endif
        </div>
    </div>
@stop

@section('content')
    <div class="row">
        <div class="col-md-6">
            <div class="card">
                <form method="post" action="{{ route('user.store') }}" autocomplete="off">
                    <div class="card-body">
                        @csrf
                        @method('POST')

                        <div class="form-group{{ $errors->has('name') ? ' has-danger' : '' }}">
                            <label>Name</label>
                            <input type="text" name="name" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" value="{{ old('name') }}">
                            @error('name')
                                <p class="small text-danger">{{ $message }}</p>
                            @enderror
                        </div>

                        <div class="form-group{{ $errors->has('email') ? ' has-danger' : '' }}">
                            <label>E-Mail</label>
                            <input type="email" name="email" class="form-control{{ $errors->has('email') ? ' is-invalid' : '' }}" value="{{ old('email') }}">
                            @error('email')
                                <p class="small text-danger">{{ $message }}</p>
                            @enderror
                        </div>

                        <div class="form-group{{ $errors->has('password') ? ' has-danger' : '' }}">
                            <label>Password</label>
                            <input type="password" name="password" class="form-control{{ $errors->has('password') ? ' is-invalid' : '' }}">
                            @error('password')
                                <p class="small text-danger">{{ $message }}</p>
                            @enderror
                        </div>

                        <div class="form-group{{ $errors->has('password_confirmation') ? ' has-danger' : '' }}">
                            <label>Password confirmation</label>
                            <input type="password" name="password_confirmation" class="form-control{{ $errors->has('password_confirmation') ? ' is-invalid' : '' }}">
                            @error('password_confirmation')
                                <p class="small text-danger">{{ $message }}</p>
                            @enderror
                        </div>

                        <div class="col-6">
                            <label>Role</label>
                            @error('roles')
                                <p class="small text-danger">{{ $message }}</p>
                            @enderror
                            @foreach($roles as $role)
                            <div class="form-group clearfix{{ $errors->has('roles') ? ' has-danger' : '' }}">
                                <div class="@if($role->name == 'Super-Admin') icheck-primary @elseif($role->name == 'Pegawai') icheck-success @elseif($role->name == 'Produksi') icheck-warning @else icheck-danger @endif d-inline">
                                    <input type="radio" id="{{ $role->id }}" name="roles" value="{{ $role->name }}" @if(old('roles') == $role->name) checked @elseif($role->name == 'Pegawai') checked @endif>
                                    <label for="{{ $role->id }}">
                                        {{ $role->name }}
                                    </label>
                                </div>
                            </div>
                            @endforeach
                        </div>

                    </div>
                    <div class="card-footer">
                        <button type="submit" class="btn btn-fill btn-primary"><i class="fas fa-save"></i> Create</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/superadmin/user/edit.blade.php
@extends('adminlte::page')

@section('title', 'Edit User')

@section('content_header')
    <div class="row">
        <div class="col-md-6">
            <h1 class="m-0 text-dark d-inline">Edit user</h1>
            <a href="{{ route('user.index') }}" class="btn btn-secondary float-right"><i class="fas fa-arrow-left"></i> Back</a>

            @if(session('success'))
                <div class="alert alert-success alert-block mt-4">
                    <button type="button" class="close" data-dismiss="alert">×</button>
                    <strong>{{ session('success') }}</strong>
                </div>
            @endif
        </div>
    </div>
@stop

@section('content')
    <div class="row">
        <div class="col-md-6">
            <div class="card">
                <form method="post" action="{{ route('user.update', $user->id) }}" autocomplete="off">
                    <div class="card-body">
                        @csrf
                        @method('PUT')

                        <div class="form-group{{ $errors->has('name') ? ' has-danger' : '' }}">
                            <label>Name</label>
                            <input type="text" name="name" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" value="{{ $user->name }}">
                            @error('name')
                                <p class="small text-danger">{{ $message }}</p>
                            @enderror
                        </div>

                        <div class="form-group{{ $errors->has('email') ? ' has-danger' : '' }}">
                            <label>E-Mail</label>
                            <input type="email" name="email" class="form-control{{ $errors->has('email') ? ' is-invalid' : '' }}" value="{{ $user->email }}">
                            @error('email')
                                <p class="small text-danger">{{ $message }}</p>
                            @enderror
                        </div>

                        <div class="form-group{{ $errors->has('password') ? ' has-danger' : '' }}">
                            <label>Password</label>
                            <input type="password" name="password" class="form-control{{ $errors->has('password') ? ' is-invalid' : '' }}">
                            @error('password')
                                <p class="small text-danger">{{ $message }}</p>
                            @enderror
                        </div>

                        <div class="form-group{{ $errors->has('password_confirmation') ? ' has-danger' : '' }}">
                            <label>Password confirmation</label>
                            <input type="password" name="password_confirmation" class="form-control{{ $errors->has('password_confirmation') ? ' is-invalid' : '' }}">
                            @error('password_confirmation')
                                <p class="small text-danger">{{ $message }}</p>
                            @enderror
                        </div>

                        <div class="col-6">
                            <label>Role</label>
                            @error('roles')
                                <p class="small text-danger">{{ $message }}</p>
                            @enderror
                            @foreach($roles as $role)
                                <div class="form-group clearfix{{ $errors->has('roles') ? ' has-danger' : '' }}">
                                    <div class="@if($role->name == 'Super-Admin') icheck-primary @elseif($role->name == 'Pegawai') icheck-success @elseif($role->name == 'Produksi') icheck-warning @else icheck-danger @endif d-inline d-inline">
                                        <input type="radio" id="{{ $role->id }}" name="roles" value="{{ $role->name }}" @if($user->roles[0]->name == $role->name) checked @elseif($role->name == 'Pegawai') checked @endif>
                                        <label for="{{ $role->id }}">
                                            {{ $role->name }}
                                        </label>
                                    </div>
                                </div>
                            @endforeach
                        </div>

                    </div>
                    <div class="card-footer">
                        <button type="submit" class="btn btn-fill btn-primary"><i class="fas fa-edit"></i> Update</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/superadmin/user/index.blade.php
@extends('adminlte::page')

@section('title', 'Users Page')

@section('content_header')
	<div class="row">
		<div class="col-12">
			<h1 class="m-0 text-dark d-inline">List of users</h1>
			<a href="{{ route('user.create') }}" class="btn btn-success float-right"><i class="fas fa-plus"></i> Create</a>
		</div>
	</div>

    @if(session('success'))
        <div class="alert alert-success alert-block mt-4">
            <button type="button" class="close" data-dismiss="alert">×</button>
            <strong>{{ session('success') }}</strong>
        </div>
    @endif

    @if(session('error'))
        <div class="alert alert-danger alert-block mt-4">
            <button type="button" class="close" data-dismiss="alert">×</button>
            <strong>{{ session('error') }}</strong>
        </div>
    @endif
@stop

@section('content')
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <table id="dataTableUser" class="table table-striped table-hover" style="width:100%">
                        <thead>
                            <tr>
                                <th>No</th>
                                <th>Name</th>
                                <th>Email</th>
                                <th>Role</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($users as $user)
                            <tr>
                                <td>{{ $loop->iteration }}</td>
                                <td>{{ $user->name }}</td>
                                <td>{{ $user->email }}</td>
                                <td>
                                    @foreach($user->roles as $role)
                                    <span class="badge @if($role->name == 'Super-Admin') bg-primary @elseif($role->name == 'Pegawai') bg-success @elseif($role->name == 'Suplier') bg-danger @else bg-warning text-white @endif">
                                        {{ $role->name }}
                                    </span>
                                    @endforeach
                                </td>
                                <td>
                                    {{-- <form action="{{ route('user.destroy', $user->id) }}" method="post" class="d-inline"> --}}
                                        <div class="btn-group">
                                            <a href="{{ route('user.edit', $user->id) }}" class="btn btn-warning btn-sm">
                                                <i class="fas fa-edit text-white"></i>
                                            </a>
                                            {{-- @csrf --}}
                                            {{-- @method('DELETE') --}}
                                            {{-- <button class="btn btn-sm btn-danger"> --}}
                                                {{-- <i class="fas fa-trash text-white"></i> --}}
                                            {{-- </button> --}}
                                        </div>
                                    </form>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@stop

@section('css')
    <!-- <link rel="stylesheet" href="/css/admin_custom.css"> -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.22/css/dataTables.bootstrap4.min.css">
@stop

@section('js')
    <script>
        $(document).ready(() => {
            $('#dataTableUser').DataTable();
        })
    </script>
    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.22/js/dataTables.bootstrap4.min.js"></script>
@stop