routes/web.php
<?php

use Illuminate\Support\Facades\Route;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('welcome');

Auth::routes(['verify' => true]);

// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('/email/verify', function () {
    return view('auth.verify');
})->middleware('auth')->name('verification.notice');

Route::get('/forgot-password', function () {
    return view('auth.passwords.email');
})->middleware('guest')->name('password.request');









// superadmin
Route::group([
	'middleware' => ['role:Super-Admin', 'auth', 'verified'],
	'prefix'     => 'super-admin',
], function () {
    Route::get('/', [App\Http\Controllers\Superadmin\DashboardController::class, 'index'])->name('super-admin.page');
    Route::resource('role', App\Http\Controllers\Superadmin\RoleController::class);
    Route::resource('user', App\Http\Controllers\Superadmin\UserController::class, [
    	'except' => [
    		'destroy',
    		'show',
    	],
    ]);
    Route::resource('size', App\Http\Controllers\Superadmin\SizeController::class);
    Route::resource('category', App\Http\Controllers\Superadmin\CategoryController::class);
    Route::resource('ingredient', App\Http\Controllers\Superadmin\IngredientController::class);
    Route::resource('product', App\Http\Controllers\Superadmin\ProductController::class, [
		'except' => [
			'edit',
			'update',
		],
		'names'  => [
			'index'   => 'superadmin-product.index',
			'create'  => 'superadmin-product.create',
			'store'   => 'superadmin-product.store',
			'show'    => 'superadmin-product.show',
			'destroy' => 'superadmin-product.destroy',
    	],
    ]);
    Route::get('laporan', [App\Http\Controllers\Superadmin\LaporanController::class, 'index'])->name('superadmin.laporan');
    Route::get('laporan/generate-ingredient-terpakai', [App\Http\Controllers\Superadmin\LaporanController::class, 'generateIngredientTerpakai'])->name('superadmin.laporan-ingredient-terpakai');

	Route::get('ingredient-image/{ingredientId}', [App\Http\Controllers\Superadmin\IngredientImageController::class, 'getImageItemsByItem'])->name('ingredient-image');
	Route::post('ingredient-image/{ingredientId}', [App\Http\Controllers\Superadmin\IngredientImageController::class, 'storeImageItemsByItem'])->name('ingredient-image.store');
	Route::delete('ingredient-image/{ingredientId}', [App\Http\Controllers\Superadmin\IngredientImageController::class, 'deleteImageItemsById'])->name('ingredient-image.destroy');

	Route::get('update-from-email/{productId}', [App\Http\Controllers\Superadmin\ProductController::class, 'updateFromEmail'])->name('superadmin.update-from-email');
	Route::get('restock', [App\Http\Controllers\Superadmin\RestockController::class, 'index'])->name('superadmin-restock.index');
	Route::get('accept-restock/{id}', [App\Http\Controllers\Superadmin\RestockController::class, 'acceptRestock'])->name('accept-restock');
});









// produksi
Route::group([
	'middleware' => ['role:Produksi', 'auth', 'verified'],
	'prefix'     => 'produksi',
], function () {
    Route::get('/', [App\Http\Controllers\Produksi\DashboardController::class, 'index'])->name('produksi.page');
    Route::get('ingredient', [App\Http\Controllers\Produksi\IngredientController::class, 'index'])->name('produksi-ingredient.index');
    Route::get('ingredient-image/{id}', [App\Http\Controllers\Produksi\IngredientController::class, 'image'])->name('produksi-ingredient-image');
    Route::resource('product', App\Http\Controllers\Produksi\ProductController::class, [
		'except' => [
			'edit',
			'update',
		],
		'names'  => [
			'index'   => 'produksi-product.index',
			'create'  => 'produksi-product.create',
			'store'   => 'produksi-product.store',
			'show'    => 'produksi-product.show',
			'destroy' => 'produksi-product.destroy',
    	]
    ]);
});









// pegawai
Route::group([
	'middleware' => ['role:Pegawai', 'auth', 'verified'],
	'prefix'     => 'pegawai',
], function () {
    Route::get('/', [App\Http\Controllers\Pegawai\DashboardController::class, 'index'])->name('pegawai.page');
    Route::resource('suplier', App\Http\Controllers\Pegawai\SuplierController::class, [
    	'except' => [
    		'destroy',
    		'show',
    	],
    ]);
    Route::resource('ingredient', App\Http\Controllers\Pegawai\IngredientController::class, [
		'except' => [
			'show',
		],
		'names'  => [
			'index'   => 'pegawai-ingredient.index',
			'create'  => 'pegawai-ingredient.create',
			'store'   => 'pegawai-ingredient.store',
			'edit'    => 'pegawai-ingredient.edit',
			'update'  => 'pegawai-ingredient.update',
			'destroy' => 'pegawai-ingredient.destroy',
    	]
    ]);

	Route::get('ingredient-image/{id}', [App\Http\Controllers\Pegawai\IngredientController::class, 'getImageItemsByItem'])->name('pegawai-ingredient-image');
	Route::post('ingredient-image/{id}', [App\Http\Controllers\Pegawai\IngredientController::class, 'storeImageItemsByItem'])->name('pegawai-ingredient-image.store');
	Route::delete('ingredient-image/{id}', [App\Http\Controllers\Pegawai\IngredientController::class, 'deleteImageItemsById'])->name('pegawai-ingredient-image.destroy');
});









// suplier
Route::group([
	'middleware' => ['role:Suplier', 'auth', 'verified'],
	'prefix'     => 'suplier',
], function () {
    Route::get('/', [App\Http\Controllers\Suplier\DashboardController::class, 'index'])->name('suplier.page');
    Route::get('ingredient', [App\Http\Controllers\Suplier\IngredientController::class, 'index'])->name('suplier-ingredient.index');
    Route::get('ingredient-image/{id}', [App\Http\Controllers\Suplier\IngredientController::class, 'image'])->name('suplier-ingredient-image');
    Route::resource('/restock', App\Http\Controllers\Suplier\RestockController::class, [
		'except' => [
			'edit',
			'update',
		],
		'names'  => [
			'index'   => 'suplier-restock.index',
			'create'  => 'suplier-restock.create',
			'store'   => 'suplier-restock.store',
			'destroy' => 'suplier-restock.destroy',
    	]
    ]);
});

app/Http/Controllers/Pegawai/DashboardController.php
<?php

namespace App\Http\Controllers\Pegawai;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class DashboardController extends Controller
{
	public function index()
	{
		return view('pegawai.dashboard');
	}
}

app/Http/Controllers/Pegawai/IngredientController.php
<?php

namespace App\Http\Controllers\Pegawai;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Ingredient;
use App\Models\IngredientImage;
use App\Models\Category;
use App\Models\User;
use App\Models\Size;
use Storage;

class IngredientController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $ingredients = Ingredient::with('suplier')
                       ->with('category')
                       ->with('size')
                       ->orderBy('suplier_id', 'desc')
                       ->get();

        return view('pegawai.ingredient.index', ['ingredients' => $ingredients]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all();
        $supliers   = User::whereHas('roles', function ($query) {
                        $query->where('roles.name', 'Suplier');
                      })->get();
        $sizes      = Size::all();

        return view('pegawai.ingredient.create', [
            'categories' => $categories,
            'supliers'   => $supliers,
            'sizes'      => $sizes,
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'category_id' => 'required',
            'suplier_id'  => 'required',
            'size_id'     => 'required',
            'name'        => 'required',
            'price'       => 'required',
            'quantity'    => 'required',
        ]);

        Ingredient::create($request->all());

        return redirect()->back()->with('success', 'Ingredient created!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $ingredient = Ingredient::find($id);
        $categories = Category::all();
        $supliers   = User::whereHas('roles', function ($query) {
                        $query->where('roles.name', 'Suplier');
                      })->get();
        $sizes      = Size::all();

        return view('pegawai.ingredient.edit', [
            'ingredient' => $ingredient,
            'categories' => $categories,
            'supliers'   => $supliers,
            'sizes'      => $sizes,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'category_id' => 'required',
            'suplier_id'  => 'required',
            'size_id'     => 'required',
            'name'        => 'required',
            'price'       => 'required',
            'quantity'    => 'required',
        ]);

        Ingredient::find($id)->update($request->all());

        return redirect()->back()->with('success', 'Ingredient updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $ingredient = Ingredient::find($id);

        $ingredient->ingredientImages->map(function ($image) {
            Storage::delete($image->path);
            $image->delete();
        });

        $ingredient->delete();

        return redirect()->back()->with('success', 'Ingredient successfully removed!');
    }

    // get image items by ingredient
    public function getImageItemsByItem($ingredientId)
    {
        $ingredient = Ingredient::with('ingredientImages')->find($ingredientId);

        return view('pegawai.ingredient.ingredient-image', [
            'ingredient' => $ingredient,
        ]);
    }

    // store image items by item
    public function storeImageItemsByItem(Request $request, $ingredientId)
    {
        $request->validate([
            'image' => 'required|file|max:2000',
        ]);

        $path = Storage::putFile(
                    'public/images',
                    $request->file('image'),
                );

        IngredientImage::create([
            'ingredient_id' => $ingredientId,
            'path'          => $path,
        ]);

        return redirect()->back()->with('success', 'Image item uploaded!');
    }

    public function deleteImageItemsById($imageItem)
    {
        $file = IngredientImage::find($imageItem);

        Storage::delete($file->path);
        $file->delete();

        return redirect()->back()->with('success', 'Image item removed!');
    }
}

app/Http/Controllers/Pegawai/SuplierController.php
<?php

namespace App\Http\Controllers\Pegawai;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\User;
use Hash;

class SuplierController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::whereHas('roles', function ($query) {
            $query->where('name', 'Suplier');
        })->get();


        return view('pegawai.suplier.index', [
            'supliers' => $users,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('pegawai.suplier.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name'     => 'required|string|max:255',
            'email'    => 'required|string|email|max:255|unique:users',
            'password' => 'required|string|min:8|confirmed',
        ]);

        $user = User::create([
            'name'     => $request->name,
            'email'    => $request->email,
            'password' => Hash::make($request->password),
        ]);

        $user->assignRole('Suplier');

        return redirect()->back()->with('success', 'Suplier created!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $suplier = User::find($id);

        return view('pegawai.suplier.edit', [
            'suplier' => $suplier,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'name'     => 'required|string|max:255',
            'email'    => 'required|string|email|max:255',
            'password' => 'confirmed',
        ]);

        $user = User::find($id);

        if ($request->password != null) {
            $password = Hash::make($request->password);
        } else {
            $password = $user->password;
        }

        $user->update([
            'name'     => $request->name,
            'email'    => $request->email,
            'password' => $password,
        ]);

        return redirect()->back()->with('success', 'Suplier updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Suplier/DashboardController.php
<?php

namespace App\Http\Controllers\Suplier;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class DashboardController extends Controller
{
    // index
    public function index()
    {
    	return view('suplier.dashboard');
    }
}

app/Http/Controllers/Suplier/IngredientController.php
<?php

namespace App\Http\Controllers\Suplier;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Ingredient;

class IngredientController extends Controller
{
	public function index(Request $request)
	{
		$ingredients = Ingredient::with(['category', 'size'])
					   ->where('suplier_id', $request->user()->id)
					   ->get();

		return view('suplier.ingredient.index', [
			'ingredients' => $ingredients,
		]);
	}

	public function image($id)
	{
        $ingredient = Ingredient::with('ingredientImages')->find($id);

        return view('suplier.ingredient.ingredient-image', ['ingredient' => $ingredient]);
	}
}

resources/views/pegawai/suplier/create.blade.php
@extends('adminlte::page')

@section('title', 'Create Suplier')

@section('content_header')
    <div class="row">
        <div class="col-md-6">
            <h1 class="m-0 text-dark d-inline">Create suplier</h1>
            <a href="{{ route('suplier.index') }}" class="btn btn-secondary float-right"><i class="fas fa-arrow-left"></i> Back</a>

            @if(session('success'))
                <div class="alert alert-success alert-block mt-4">
                    <button type="button" class="close" data-dismiss="alert">×</button>
                    <strong>{{ session('success') }}</strong>
                </div>
            @endif
        </div>
    </div>
@stop

@section('content')
    <div class="row">
        <div class="col-md-6">
            <div class="card">
                <form method="post" action="{{ route('suplier.store') }}" autocomplete="off">
                    <div class="card-body">
                        @csrf
                        @method('POST')

                        <div class="form-group{{ $errors->has('name') ? ' has-danger' : '' }}">
                            <label>Name</label>
                            <input type="text" name="name" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" value="{{ old('name') }}">
                            @error('name')
                                <p class="small text-danger">{{ $message }}</p>
                            @enderror
                        </div>

                        <div class="form-group{{ $errors->has('email') ? ' has-danger' : '' }}">
                            <label>E-Mail</label>
                            <input type="email" name="email" class="form-control{{ $errors->has('email') ? ' is-invalid' : '' }}" value="{{ old('email') }}">
                            @error('email')
                                <p class="small text-danger">{{ $message }}</p>
                            @enderror
                        </div>

                        <div class="form-group{{ $errors->has('password') ? ' has-danger' : '' }}">
                            <label>Password</label>
                            <input type="password" name="password" class="form-control{{ $errors->has('password') ? ' is-invalid' : '' }}">
                            @error('password')
                                <p class="small text-danger">{{ $message }}</p>
                            @enderror
                        </div>

                        <div class="form-group{{ $errors->has('password_confirmation') ? ' has-danger' : '' }}">
                            <label>Password confirmation</label>
                            <input type="password" name="password_confirmation" class="form-control{{ $errors->has('password_confirmation') ? ' is-invalid' : '' }}">
                            @error('password_confirmation')
                                <p class="small text-danger">{{ $message }}</p>
                            @enderror
                        </div>

                    </div>
                    <div class="card-footer">
                        <button type="submit" class="btn btn-fill btn-primary"><i class="fas fa-save"></i> Create</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/pegawai/suplier/edit.blade.php
@extends('adminlte::page')

@section('title', 'Edit Suplier')

@section('content_header')
    <div class="row">
        <div class="col-md-6">
            <h1 class="m-0 text-dark d-inline">Edit suplier</h1>
            <a href="{{ route('suplier.index') }}" class="btn btn-secondary float-right"><i class="fas fa-arrow-left"></i> Back</a>

            @if(session('success'))
                <div class="alert alert-success alert-block mt-4">
                    <button type="button" class="close" data-dismiss="alert">×</button>
                    <strong>{{ session('success') }}</strong>
                </div>
            @endif
        </div>
    </div>
@stop

@section('content')
    <div class="row">
        <div class="col-md-6">
            <div class="card">
                <form method="post" action="{{ route('suplier.update', $suplier->id) }}" autocomplete="off">
                    <div class="card-body">
                        @csrf
                        @method('PUT')

                        <div class="form-group{{ $errors->has('name') ? ' has-danger' : '' }}">
                            <label>Name</label>
                            <input type="text" name="name" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" value="{{ $suplier->name }}">
                            @error('name')
                                <p class="small text-danger">{{ $message }}</p>
                            @enderror
                        </div>

                        <div class="form-group{{ $errors->has('email') ? ' has-danger' : '' }}">
                            <label>E-Mail</label>
                            <input type="email" name="email" class="form-control{{ $errors->has('email') ? ' is-invalid' : '' }}" value="{{ $suplier->email }}">
                            @error('email')
                                <p class="small text-danger">{{ $message }}</p>
                            @enderror
                        </div>

                        <div class="form-group{{ $errors->has('password') ? ' has-danger' : '' }}">
                            <label>Password</label>
                            <input type="password" name="password" class="form-control{{ $errors->has('password') ? ' is-invalid' : '' }}">
                            @error('password')
                                <p class="small text-danger">{{ $message }}</p>
                            @enderror
                        </div>

                        <div class="form-group{{ $errors->has('password_confirmation') ? ' has-danger' : '' }}">
                            <label>Password confirmation</label>
                            <input type="password" name="password_confirmation" class="form-control{{ $errors->has('password_confirmation') ? ' is-invalid' : '' }}">
                            @error('password_confirmation')
                                <p class="small text-danger">{{ $message }}</p>
                            @enderror
                        </div>

                    </div>
                    <div class="card-footer">
                        <button type="submit" class="btn btn-fill btn-primary"><i class="fas fa-edit"></i> Update</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/pegawai/suplier/index.blade.php
@extends('adminlte::page')

@section('title', 'Supliers Page')

@section('content_header')
	<div class="row">
		<div class="col-12">
			<h1 class="m-0 text-dark d-inline">List of supliers</h1>
			<a href="{{ route('suplier.create') }}" class="btn btn-success float-right"><i class="fas fa-plus"></i> Create</a>
		</div>
	</div>

    @if(session('success'))
        <div class="alert alert-success alert-block mt-4">
            <button type="button" class="close" data-dismiss="alert">×</button>
            <strong>{{ session('success') }}</strong>
        </div>
    @endif

    @if(session('error'))
        <div class="alert alert-danger alert-block mt-4">
            <button type="button" class="close" data-dismiss="alert">×</button>
            <strong>{{ session('error') }}</strong>
        </div>
    @endif
@stop

@section('content')
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <table id="dataTableUser" class="table table-striped table-hover" style="width:100%">
                        <thead>
                            <tr>
                                <th>No</th>
                                <th>Name</th>
                                <th>Email</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($supliers as $suplier)
                            <tr>
                                <td>{{ $loop->iteration }}</td>
                                <td>{{ $suplier->name }}</td>
                                <td>{{ $suplier->email }}</td>
                                <td>
                                    <div class="btn-group">
                                        <a href="{{ route('suplier.edit', $suplier->id) }}" class="btn btn-warning btn-sm">
                                            <i class="fas fa-edit text-white"></i>
                                        </a>
                                    </div>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@stop

@section('css')
    <!-- <link rel="stylesheet" href="/css/admin_custom.css"> -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.22/css/dataTables.bootstrap4.min.css">
@stop

@section('js')
    <script>
        $(document).ready(() => {
            $('#dataTableUser').DataTable();
        })
    </script>
    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.22/js/dataTables.bootstrap4.min.js"></script>
@stop